spring.application.name=backend
server.port=9090
spring.datasource.url=jdbc:mysql://localhost:3306/Clinique?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true